# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90b10c2d57fe05dd879e8806b74bb897b6558428ef0a752128be5283baa8c0f7a109f69fe6605a472765dac69a17fb85521043ee7824a599fefe309ebccfe6b0

test:
  secret_key_base: ae3e4fdddfe8d27d2c2e4bcca27b9988947791f474e397a3bf29fbfe22c697bc720b52f86355264c16eecbb33c3683e47e483630a0a173ef186220a1f3e8d371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
